// HTML validator for wireframe variations generated by Track A (Vision pipeline).
// Checks:
//  1. <section> root element present
//  2. All CSS classes are known pxpace.css classes (or inline-style exceptions)
//  3. All data-slot values are known slots for the given SectionType
//  4. Required slots are present in the HTML
//
// Does NOT require a DOM parser — uses regex, good enough for clean AI output.

import fs from "fs/promises"
import path from "path"
import { getSlotSchema, getRequiredSlots, isKnownSlot } from "./slot-schema"
import type { SectionType } from "@/lib/types/wireframe"

export type HtmlValidationResult = {
  valid: boolean
  errors: string[]    // blocking — generation should retry
  warnings: string[]  // non-blocking — logged but not retried
}

const SHARED_DIR = path.join(process.cwd(), "wireframe-library", "_shared")
const SHARED_CSS_FILES = [
  "pxpace.css",
  "wireframe-components.css",
  "wireframe-base.css",
]

// Cached set of all known class names across shared CSS files.
let cachedKnownClasses: Set<string> | null = null

async function getKnownClasses(): Promise<Set<string>> {
  if (cachedKnownClasses) return cachedKnownClasses

  const classes = new Set<string>()
  // Match class selectors: .class-name{ or .class-name  or .class-name, or .class-name:
  // Allow BEM-style: .wf-foo__bar, .wf-foo--mod, .wf-foo-1
  const pattern = /\.([a-zA-Z][a-zA-Z0-9_-]*(?:__[a-zA-Z0-9_-]+)?(?:--[a-zA-Z0-9_-]+)*)\s*[{,:>\s]/g

  for (const filename of SHARED_CSS_FILES) {
    const filePath = path.join(SHARED_DIR, filename)
    let css: string
    try {
      css = await fs.readFile(filePath, "utf-8")
    } catch {
      continue // file optional
    }
    let m: RegExpExecArray | null
    while ((m = pattern.exec(css)) !== null) {
      classes.add(m[1])
    }
  }

  cachedKnownClasses = classes
  return classes
}

/** Clear class cache (test/dev use). */
export function clearPxpaceClassCache(): void {
  cachedKnownClasses = null
}

export async function validateWireframeHtml(
  html: string,
  type: SectionType,
): Promise<HtmlValidationResult> {
  const errors: string[] = []
  const warnings: string[] = []

  // 1. <section present (file may be full HTML page or bare fragment)
  if (!/<section[\s>]/i.test(html)) {
    errors.push('HTML must contain a <section> element')
  }

  // 2. Extract all class="" values
  const knownClasses = await getKnownClasses()
  const classPattern = /class="([^"]*)"/g
  const unknownClasses = new Set<string>()
  let cm: RegExpExecArray | null
  while ((cm = classPattern.exec(html)) !== null) {
    const classList = cm[1].trim().split(/\s+/).filter(Boolean)
    for (const cls of classList) {
      if (!knownClasses.has(cls)) {
        unknownClasses.add(cls)
      }
    }
  }
  if (unknownClasses.size > 0) {
    warnings.push(`Unknown CSS classes (should only use pxpace.css + wireframe-components.css): ${[...unknownClasses].slice(0, 10).join(", ")}${unknownClasses.size > 10 ? ` ...+${unknownClasses.size - 10} more` : ""}`)
  }

  // 3. Extract all data-slot values
  const slotPattern = /data-slot="([^"]*)"/g
  const slotsFound = new Set<string>()
  let sm: RegExpExecArray | null
  while ((sm = slotPattern.exec(html)) !== null) {
    slotsFound.add(sm[1])
  }

  // 4. Check each found slot is known
  const knownSchema = getSlotSchema(type)
  if (knownSchema.length > 0) {
    for (const key of slotsFound) {
      if (!isKnownSlot(type, key)) {
        errors.push(`Unknown data-slot key: "${key}" (not in slot schema for ${type})`)
      }
    }

    // 5. Check required slots present
    const required = getRequiredSlots(type)
    for (const slot of required) {
      if (!slotsFound.has(slot.key)) {
        errors.push(`Required slot missing: "${slot.key}"`)
      }
    }
  } else {
    warnings.push(`No slot schema defined for type "${type}" — slot validation skipped`)
  }

  // 6. Warn if no slots found at all (probably AI forgot data-slot)
  if (slotsFound.size === 0) {
    errors.push("No data-slot attributes found — AI forgot to add slot markers")
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
  }
}

/** Quick summary of what slots the HTML uses (for meta.json slots[] field). */
export function extractUsedSlotKeys(html: string): string[] {
  const found: string[] = []
  const pattern = /data-slot="([^"]*)"/g
  let m: RegExpExecArray | null
  while ((m = pattern.exec(html)) !== null) {
    found.push(m[1])
  }
  return [...new Set(found)]
}
